name: Test Reusable workflow with inputs and outputs 
# we have to call the reusable workflow inside a job to use the outputs in another job.
on:
  workflow_dispatch
jobs:   
  job1: 
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/inputs_and_outputs.yml@main
    with:
      input1: an_input
  use_outputs_from_job1:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}      
