name: Test Reusable workflow with inputs and outputs 

on:
  workflow_dispatch
jobs:   
  job1: 
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/inputs_and_outputs.yml@main
  use_outputs_from_job1:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}      
