name: Test reusable workflow with secrets and variables
on:
  workflow_dispatch
jobs:
  job1:
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/secrets_and_vars.yml@main
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      repo_s: ${{ secrets.repo_secret }}       
      org_s: ${{ secrets.org_secret }}    
  print_done:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo test done.
      
