name: Test reusable workflow with secrets and variables
on:
  workflow_dispatch
jobs:
  job1:
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/secrets_and_vars.yml@main
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      repo_s: ${{ secrets.repo_secret }}       
      org_s: ${{ secrets.org_secret }}    
  print_done:
    runs-on: ubuntu-latest
    needs: job1
    environment:
      name: dev
    steps:
      - run: echo ${{secrets.env_dev_secret}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
     # - run: echo ${{secrets.org_secret}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
     # - run: echo ${{secrets.ORG_SECRET}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      # the variables defined at the repository or organization level will be available in called workflow
      # We do not need to pass these vars to the called workfloww
      - run: echo ${{vars.repo_var}} # a variable defined at the repository level
      - run: echo ${{vars.org_var}} # a variable defined at the organization level
      - run: echo test done.
      
