name: Reusable workflow example

on:
  workflow_dispatch
jobs:   
  job1:
    runs-on: ubuntu-latest 
    Shahuss1115/reusable-workflows/.github/workflows/test.yml@main
  use_outputs_from_job1:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}      